# configs/config.yaml
cuda_visible_devices: [ 0 ]
training_model: "Baseline"
training_dataset: "WHU"
seed: 42
#folder: "/public/fysun/Multimodal/Modal-Fusion/Dataset"  # your dataset path


hydra:
  run:
    dir: "./${training_model}_${training_dataset}_${seed}/${now:%Y-%m-%d_%H-%M-%S}"
  job:
    chdir: true
  job_logging:
    capture_stdout: true

model:
  pretrained: true
  model_dim: 512
  num_heads: 8
  ffn_dim: 2048
  dropout: 0.5
  num_layers: 1
  backbone: "mit_b4"
  decoder_embed_dim: 512
  pretrained_backbone: "${folder}/pretrained/mit_b4.pth"
  bn_eps: 0.01
  bn_momentum: 0.01

training:
  epochs: 100
  save_epoch: 100
  batch_size: 10
  learning_rate: 0.01
  weight_decay: 0.0005
  momentum: 0.9
  milestones: [ 25, 35, 45 ]
  window_size: [ 256, 256 ]
  num_workers: 0
  cache: True
  augmentation: True
  alpha: 0.01
  beta: 0.05
  gamma: 0.5

dataset:
  name: ${training_dataset}
  datasets:
    Vaihingen:
      name: "Vaihingen"
      labels: [ "roads", "buildings", "low veg.", "trees", "cars", "clutter" ]
      n_classes: 6
      stride_size: 32
      main_folder: "${folder}/Vaihingen"
      data_folder: "${.main_folder}/top/top_mosaic_09cm_area{}.tif"
      dsm_folder: "${.main_folder}/dsm/dsm_09cm_matching_area{}.tif"
      label_folder: "${.main_folder}/gts_for_participants/top_mosaic_09cm_area{}.tif"
      eroded_folder: "${.main_folder}/gts_eroded_for_participants/top_mosaic_09cm_area{}_noBoundary.tif"
      train_ids: [ '1', '3', '23', '26', '7', '11', '13', '28', '17', '32', '34', '37' ]
      test_ids: [ '5', '21', '15', '30' ]
      num_train_imgs: 10000
      palette:
        0: [ 255, 255, 255 ]  # Impervious surfaces (white)
        1: [ 0, 0, 255 ]      # Buildings (blue)
        2: [ 0, 255, 255 ]    # Low vegetation (cyan)
        3: [ 0, 255, 0 ]      # Trees (green)
        4: [ 255, 255, 0 ]    # Cars (yellow)
        5: [ 255, 0, 0 ]      # Clutter (red)
        6: [ 0, 0, 0 ]        # Undefined (black)
    Potsdam:
      name: "Potsdam"
      labels: [ "roads", "buildings", "low veg.", "trees", "cars", "clutter" ]
      n_classes: 6
      stride_size: 128
      main_folder: "${folder}/Potsdam/"
      data_folder: "${.main_folder}/4_Ortho_RGBIR/top_potsdam_{}_RGBIR.tif"
      dsm_folder: "${.main_folder}/1_DSM_normalisation/dsm_potsdam_{}_normalized_lastools.jpg"
      label_folder: "${.main_folder}/5_Labels_for_participants/top_potsdam_{}_label.tif"
      eroded_folder: "${.main_folder}/5_Labels_for_participants_no_Boundary/top_potsdam_{}_label_noBoundary.tif"
      train_ids: [ '6_10', '7_10', '2_12', '3_11', '2_10', '7_8', '5_10', '3_12', '5_12', '7_11', '7_9', '6_9', '7_7', '4_12', '6_8', '6_12', '6_7', '4_11' ]
      test_ids: [ '4_10', '5_11', '2_11', '3_10', '6_11', '7_12' ]
      num_train_imgs: 10000
      palette:
        0: [ 255, 255, 255 ]  # Impervious surfaces (white)
        1: [ 0, 0, 255 ]      # Buildings (blue)
        2: [ 0, 255, 255 ]    # Low vegetation (cyan)
        3: [ 0, 255, 0 ]      # Trees (green)
        4: [ 255, 255, 0 ]    # Cars (yellow)
        5: [ 255, 0, 0 ]      # Clutter (red)
        6: [ 0, 0, 0 ]        # Undefined (black)
    WHU:
      name: "WHU"
      labels: [ "farmland", "city", "village", "water", "forest", "road", "others", "background" ]
      n_classes: 8
      train_ids: ""
      test_ids: ""
      num_train_imgs: 7975  # 预处理函数随机波动导致
      palette:
        0: [ 204, 102, 0 ]      # Class 1 - Farmland
        1: [ 255, 0, 0 ]        # Class 2 - City
        2: [ 255, 255, 0 ]      # Class 3 - Village
        3: [ 0, 0, 255 ]        # Class 4 - Water
        4: [ 85, 167, 0 ]       # Class 5 - Forest
        5: [ 0, 255, 255 ]      # Class 6 - Road
        6: [ 153, 102, 153 ]    # Class 7 - Others
        7: [ 0, 0, 0 ]          # Undefined (black)
    YESeg:
      name: "YESeg"
      labels: [ "bare ground", "low vegetation", "trees", "houses", "water", "roads", "others", "background" ]
      n_classes: 8
      train_ids: ""
      test_ids: ""
      num_train_imgs: 1784
      palette:
        0: [ 128, 0, 0 ]      # Class 1 - bare ground
        1: [ 0, 128, 0 ]        # Class 2 - low vegetation
        2: [ 128, 128, 0 ]      # Class 3 - trees
        3: [ 0, 0, 128 ]        # Class 4 - houses
        4: [ 128, 0, 128 ]       # Class 5 - water
        5: [ 0, 128, 128 ]      # Class 6 - roads
        6: [ 128, 128, 128 ]    # Class 7 - others
        7: [ 0, 0, 0 ]          # Undefined (background)
    HuNan:
      name: "HuNan"
      labels: [ "bare ground", "low vegetation", "trees", "houses", "water", "roads", "others", "background" ]
      n_classes: 8
      train_ids: ""
      test_ids: ""
      num_train_imgs: 1784
      palette:
        0: [ 128, 0, 0 ]      # Class 1 - bare ground
        1: [ 0, 128, 0 ]        # Class 2 - low vegetation
        2: [ 128, 128, 0 ]      # Class 3 - trees
        3: [ 0, 0, 128 ]        # Class 4 - houses
        4: [ 128, 0, 128 ]       # Class 5 - water
        5: [ 0, 128, 128 ]      # Class 6 - roads
        6: [ 128, 128, 128 ]    # Class 7 - others
        7: [ 0, 0, 0 ]          # Undefined (background)